# Code repositories

By Xindi (Cindy) Hu and Jahred Liddie

Each study has at least one code repository that typically holds R or Python code, and research outputs (e.g., results files, tables, and figures). Repositories may also include datasets. This chapter outlines how to organize these files. Adhering to a standard format makes it easier for us to efficiently collaborate across projects. 

## Project Structure

We recommend the following example directory structure:

```
0-config.R
1 - Data-Management/
    1-prep-env-data.R
    2a-prep-covariates.R
    2b-prep-weighted.R
    3a-prep-final.R
    3b-prep-sensitivity.R
2 - Analysis/
    1 - Main-Analysis/
        1-projname-EDA.R
        2-projname-primary-analysis1.R
        3-projname-primary-analysis1.R
        4-projname-secondary-analysis.R
    2 - Assumption-Check/
    4 - Sensitivity-Analyses/
3 - Figures/
    ...
4 - Tables/
    ...
5 - Results/
    1 - Regression-Results/
        1-projname-reg-primary1.RDS
        2-projname-reg-primary2.RDS
        3-projname-mean-peakwk.RDS
        5-absentee-mean-cdph2.RDS
        6-absentee-mean-cdph3.RDS
    ...
.gitignore
.Rproj
```

For brevity, not every directory is "expanded", but we can glean some important takeaways from what we _do_ see.

## `.Rproj` files
An "R Project" can be created within RStudio by going to `File >> New Project`. Depending on where you are with your research, choose the most appropriate option. This will save preferences, working directories, and even the results of running code/data (though I'd recommend starting from scratch each time you open your project, in general). Then, ensure that whenever you are working on that specific research project, you open your created project to enable the full utility of `.Rproj` files. This also automatically sets the directory to the top level of the project. 

## Configuration ('config') File
This file can be responsible for a variety of common tasks. It can declare global variables, load functions, declare paths, and more. In this way, every file can begin with `source("0-config")`, and its role is to reduce redundancy and create an abstraction layer that allows you to make changes in one place (`0-config.R`) rather than 5 different files. Paths which will be referenced in multiple scripts (i.e. a `merged_data_path`) can be declared in `0-config.R` and simply referred to by its variable name in scripts. If you ever want to change things, rename them, or even switch from a downsample to the full data, all you would then to need to do is modify the path in one place and the change will automatically update throughout your project. See the example config file for more details. The paths defined in the `0-config.R` file assume that users have opened the `.Rproj` file, which sets the directory to the top level of the project. 

## Order Files and Directories
This makes the jumble of alphabetized filenames much more coherent and places similar code and files next to one another. This also helps us understand how data flows from start to finish and allows us to easily map a script to its output (i.e. `2 - Analysis/1 - Main-Analysis/2-projname-primary-analysis1.R` => `5 - Results/1 - Regression-Results/1-projname-reg-primary1.RDS`). If you take nothing else away from this guide, this is the single most helpful suggestion to make your workflow more coherent. Often the particular order of files will be in flux until an analysis is close to completion. At that time it is important to review file order and naming and reproduce everything prior to drafting a manuscript. 
