# AI policy

by Xindi (Cindy) Hu and Jahred Liddie

## Policy overview

This policy is meant to refer to Large-Language Models (LLMs) for text or code generation in learning and research. This document does not cover machine learning or even AI in general, as these are distinct concepts. All statements in this document are subject to revision.

Proceed with caution and purpose when using LLMs in your learning or research as a student. Our recommendation stems from the following rationale:

- LLMs are effectively a next-word prediction engine. As a result, for their statement to be true, a collection of true words have to be strung in the correct order. As the sequence of orders increases, the probability that the statement is true decreases. As a result, LLMs as tools require expertise in order to validate their output. The purpose behind your training is to develop that expertise. If you are using an LLM, you less able to effectively develop that expertise.

- Use of LLMs requires detailed validation steps, which your training may not have yet provided. So, you cannot verify whether some output is valid. This concern arises when developing code for data processing and statistical analyses.

- Part of my role is to train you. That means we should discuss questions that you have or challenges that arise. An LLM may send you down a wrong path without your realization. This is not an effective use of your limited time. Learning requires a certain amount of friction. Part of my job is to help you manage the appropriate amount of friction (enough to enhance your understanding, but not too much as to hinder you).

- Scientific writing is a difficult task that takes lots of practice to develop. Off-loading this process means you may not develop the necessary skills.

- Recent research has shown 'deskilling' or when cognitive processes are offloaded to an LLM a person's skill at a task degrades. Preventing skill development is a worse issue.

There are some cases where LLM can be more reliable. The following are some use cases that we would deem LLMs to be reliable enough as a tool:

- Translating code from one software language to another (this comes with a built-in check)

- Convert existing code into an R or Python package (which again comes with a built-in check)

- Generating boilerplate code for plots (again straightforward to check by looking at the plot)

- Vectorizing or improving existing code (another built-in check, can you see the theme?)

- Aid in debugging code

- An advanced version of a thesaurus for complex topics

Again, caution and purpose are still needed when using an LLM for many of these tasks while you are a student, and even afterwards. Doing them the "difficult way" can be a valuable learning experience. For example, the act of converting code helps you think through the process of what aspects of a tool a user might need, how a sensible API is created, and how to structure files.

Finally, I will note that you can experiment with LLMs as a tool. We have with instances outside the use cases above. As stated in the opening sentence, this document is meant to focus on the use of LLMs in your learning and research. These are (or should be) distinct from experimenting with them for different tasks. Use of LLMs should be clearly delineated behind the purpose.

Having outlined my general perspective on the use of LLMs in learning and research, the following details what is expected of you if you are going to make extensive use of an LLM for a research project despite the warnings made here.

------------------------------------------------------------------------

## Disclosure Statement

For us to have successful advisor-advisee, mentor-mentee, and even lab member-lab member relationships, we need to be able to trust each other. As part of that, it is expected of you to disclose any use of an LLM. Failure to do so jeopardizes that collaborative relationship. For disclosing LLM use, please complete the following table (or a modified version we agree upon). This table *should be completed prior to using an LLM*.

| Task                      | Rationale | Description of Use |
|---------------------------|-----------|--------------------|
| Outlining project         | ...       | ...                |
| Writing proposal or paper | ...       | ...                |
| Statistical analysis plan | ...       | ...                |
| Code writing              | ...       | ...                |
| Data analysis             | ...       | ...                |
| Code or paper review      | ...       | ...                |
| Literature review         | ...       | ...                |
| Other                     | ...       | ...                |

I (as Cindy) also recognize that the mentor-mentee relationship is a two-way street. So, I also make the following promises in terms of conduct and disclosure to you:

- I will review your work that you send to me. I will not use an LLM or other related technology for reviewing your work. In other cases, other lab members (should as postdocs) will review work that you send to them and the same expectation is appropriate regarding LLM use.

- I will respond to your emails or questions myself. I will not use an LLM to do so.

- I will draft requested recommendations letters myself and will not use an LLM.

- If we are working together on a project, I will disclose my use of an LLM in accordance with the disclosure table.

## My expectations

The following are some additional requirements if you are to use LLMs. If you want an exception to any of these steps, you must discuss them with me and I must approve.

- You are to use GW's [Gemini access](https://library.unc.edu/ai/library-ai-studio/promptlab/) to interact with an LLM. Other LLMs are acceptable as permitted by data privacy constraints.

- No data from or used by research group is uploaded, irrespective of the GW-determined Information Tier.

- No works in-progress or other similar materials are uploaded. Revising small collections of different sentences is ok, but an entire document should never be uploaded.

- Uploading lab group material (papers, manuscripts, private code) that is not yours without the express and documented permission of the owner of that material.

The following are some principles that are expected of you to adhere to if you use LLMs:

- Completed the disclosure table. This helps to ensure that you had identified a clear task for use with an LLM and are limiting it to that task.

- Export all chat logs for record keeping. This should be all relevant chat logs *in their entirety* for a project. I may ask for these to be provided to me.

- Any code generated by an LLM that cannot be directly verified is instead vetted and verified through a testing procedure. An example of code that can be directly verifiable is code to create a plot (since we can examine the plot to see whether it is correct). An example of code that is not directly verifiable is fitting a statistical model. Such code should be validated through the use of unit tests.

- LLMs are used for text revision and not text generation. A major danger with LLM text is that it might be plagiarized, which can have substantial negative professional consequences for both you and me. I may ask that you use plagiarism detection software if LLMs are used during the writing process.
